language: ruby
rvm:
  - 2.5.0
services:
  - postgresql
  - redis-server
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
#before_install:
#  - rm -f Gemfile.lock
before_script:
  - psql -c 'create database archivist_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rails db:migrate RAILS_ENV=test
addons:
  postgresql: "9.6"
